const express = require('express');
const router = express.Router();
const authMiddleware = require('../middleware/auth');
const { loginLimiter, registerLimiter } = require('../config/rateLimiter');
const { register, login, getMe, logout, debugCheckPassword } = require('../controllers/authController');
// router.post('/register', register);
// router.post('/login', login);
router.get('/me', authMiddleware, getMe);
router.post('/logout', authMiddleware, logout);
router.post('/login', loginLimiter, login);
router.post('/register', registerLimiter, register);
router.post('/debug-check', debugCheckPassword);
module.exports = router;